source "https://rubygems.org"
gem "jekyll", "~> 3.4.0"
gem "jemoji", "~> 0.8.0"
gem "jekyll-gist", "~> 1.4.0"
gem "jekyll-avatar", "~> 0.4.0"
gem "jekyll-mentions", "~> 1.2.0"
gem "jekyll-titles-from-headings", "~> 0.1.0"
gem "jekyll-redirect-from", "~> 0.12.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-feed", "~> 0.9.0"
gem "jekyll-sitemap", "~> 1.0.0"